sudo: false
language: scala

services:
- docker

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: docker-compose run test
    - name: "Integration Tests"
      script: docker-compose run integration
