sudo: true
dist: trusty
language: scala

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: docker-compose run test
    - name: "Integration Tests"
      script: docker-compose run integration
