version: '3.4'

x-sbt: &sbt
  build:
    context: .
    target: base
  volumes:
  - ".:/app"
  - "~/.ivy2:/root/.ivy2"
  - "~/.sbt:/root/.sbt"
  working_dir: /app

services:
  test:
    <<: *sbt
    command: sbt test

  integration:
    <<: *sbt
    command: sbt it:test

  app:
    build:
      context: .
      target: release
